/*  CFONBRecordBase.java - CFONB French Account Statement File
 *  @(#) $Id$
 *  Automatically generated by xtrans/web/xslt/genRecord.xsl at 2017-05-29T15:41:30+02:00
 *  DO NOT EDIT HERE - rather inherit from this class!
 */
package org.teherba.xtrans.finance;
import  org.teherba.xtrans.CharRecord;
import  org.teherba.xtrans.BaseTransformer;
import  org.teherba.xtrans.Field;
import  java.sql.Date;
import  java.sql.Timestamp;
import  org.xml.sax.Attributes;
import  org.xml.sax.helpers.AttributesImpl;
import  org.xml.sax.SAXException;

/** CFONB French Account Statement File.
 *  total length 120 Chars
 */
public class CFONBRecordBase extends CharRecord {
    public static final int RECORD_LENGTH = 120;
    /** Source code version */
    public static final String CVSID = "@(#) $Id$";


    /** No-args Constructor for CFONB French Account Statement File.
     */
    public CFONBRecordBase() {
        super();
        setRecordTag("CFONB");
    } // Constructor

    /** Field cdEnreg - code enregistrement */
    protected static final Field CDENREG = new Field(0, 2, "cdEnreg");

    /** Sets cdEnreg - code enregistrement
     *  @param cdEnreg code enregistrement
     */
    public void setCdEnreg(String cdEnreg) {
        setString(0, 2, cdEnreg);
    } // setCdEnreg

    /** Gets cdEnreg - code enregistrement
     *  @return code enregistrement
     */
    public String getCdEnreg() {
        return getString(0, 2);
    } // getCdEnreg
    //----------------
    /** Field c1CdBanque - M bank code */
    protected static final Field C1CDBANQUE = new Field(2 + 0, 5, "c1CdBanque");

    /** Sets c1CdBanque - M bank code
     *  @param c1CdBanque M bank code
     */
    public void setC1CdBanque(String c1CdBanque) {
        setString(2 + 0, 5, c1CdBanque);
    } // setC1CdBanque

    /** Gets c1CdBanque - M bank code
     *  @return M bank code
     */
    public String getC1CdBanque() {
        return getString(2 + 0, 5);
    } // getC1CdBanque
    //----------------
    /** Field c1Reserve1 - X */
    protected static final Field C1RESERVE1 = new Field(2 + 5, 4, "c1Reserve1");

    /** Sets c1Reserve1 - X
     *  @param c1Reserve1 X
     */
    public void setC1Reserve1(String c1Reserve1) {
        setString(2 + 5, 4, c1Reserve1);
    } // setC1Reserve1

    /** Gets c1Reserve1 - X
     *  @return X
     */
    public String getC1Reserve1() {
        return getString(2 + 5, 4);
    } // getC1Reserve1
    //----------------
    /** Field c1CdGuichet - M branch */
    protected static final Field C1CDGUICHET = new Field(2 + 9, 5, "c1CdGuichet");

    /** Sets c1CdGuichet - M branch
     *  @param c1CdGuichet M branch
     */
    public void setC1CdGuichet(String c1CdGuichet) {
        setString(2 + 9, 5, c1CdGuichet);
    } // setC1CdGuichet

    /** Gets c1CdGuichet - M branch
     *  @return M branch
     */
    public String getC1CdGuichet() {
        return getString(2 + 9, 5);
    } // getC1CdGuichet
    //----------------
    /** Field c1CdDevise - O currency code ISO 4217 */
    protected static final Field C1CDDEVISE = new Field(2 + 14, 3, "c1CdDevise");

    /** Sets c1CdDevise - O currency code ISO 4217
     *  @param c1CdDevise O currency code ISO 4217
     */
    public void setC1CdDevise(String c1CdDevise) {
        setString(2 + 14, 3, c1CdDevise);
    } // setC1CdDevise

    /** Gets c1CdDevise - O currency code ISO 4217
     *  @return O currency code ISO 4217
     */
    public String getC1CdDevise() {
        return getString(2 + 14, 3);
    } // getC1CdDevise
    //----------------
    /** Field c1NoChiffres - D apres la virgule du montant */
    protected static final Field C1NOCHIFFRES = new Field(2 + 17, 1, "c1NoChiffres");

    /** Sets c1NoChiffres - D apres la virgule du montant
     *  @param c1NoChiffres D apres la virgule du montant
     */
    public void setC1NoChiffres(long c1NoChiffres) {
        setNumber(2 + 17, 1, c1NoChiffres);
    } // setC1NoChiffres

    /** Gets c1NoChiffres - D apres la virgule du montant
     *  @return D apres la virgule du montant
     */
    public long getC1NoChiffres() {
        return getNumber(2 + 17, 1);
    } // getC1NoChiffres
    //----------------
    /** Field c1Reserve2 - X */
    protected static final Field C1RESERVE2 = new Field(2 + 18, 1, "c1Reserve2");

    /** Sets c1Reserve2 - X
     *  @param c1Reserve2 X
     */
    public void setC1Reserve2(String c1Reserve2) {
        setString(2 + 18, 1, c1Reserve2);
    } // setC1Reserve2

    /** Gets c1Reserve2 - X
     *  @return X
     */
    public String getC1Reserve2() {
        return getString(2 + 18, 1);
    } // getC1Reserve2
    //----------------
    /** Field c1NoCompte - M */
    protected static final Field C1NOCOMPTE = new Field(2 + 19, 11, "c1NoCompte");

    /** Sets c1NoCompte - M
     *  @param c1NoCompte M
     */
    public void setC1NoCompte(String c1NoCompte) {
        setString(2 + 19, 11, c1NoCompte);
    } // setC1NoCompte

    /** Gets c1NoCompte - M
     *  @return M
     */
    public String getC1NoCompte() {
        return getString(2 + 19, 11);
    } // getC1NoCompte
    //----------------
    /** Field c1Reserve3 - X */
    protected static final Field C1RESERVE3 = new Field(2 + 30, 2, "c1Reserve3");

    /** Sets c1Reserve3 - X
     *  @param c1Reserve3 X
     */
    public void setC1Reserve3(String c1Reserve3) {
        setString(2 + 30, 2, c1Reserve3);
    } // setC1Reserve3

    /** Gets c1Reserve3 - X
     *  @return X
     */
    public String getC1Reserve3() {
        return getString(2 + 30, 2);
    } // getC1Reserve3
    //----------------
    /** Field c1DateSolde - M DDMMYY */
    protected static final Field C1DATESOLDE = new Field(2 + 32, 6, "c1DateSolde");

    /** Sets c1DateSolde - M DDMMYY
     *  @param c1DateSolde M DDMMYY
     */
    public void setC1DateSolde(long c1DateSolde) {
        setNumber(2 + 32, 6, c1DateSolde);
    } // setC1DateSolde

    /** Gets c1DateSolde - M DDMMYY
     *  @return M DDMMYY
     */
    public long getC1DateSolde() {
        return getNumber(2 + 32, 6);
    } // getC1DateSolde
    //----------------
    /** Field c1Reserve4 - X */
    protected static final Field C1RESERVE4 = new Field(2 + 38, 50, "c1Reserve4");

    /** Sets c1Reserve4 - X
     *  @param c1Reserve4 X
     */
    public void setC1Reserve4(String c1Reserve4) {
        setString(2 + 38, 50, c1Reserve4);
    } // setC1Reserve4

    /** Gets c1Reserve4 - X
     *  @return X
     */
    public String getC1Reserve4() {
        return getString(2 + 38, 50);
    } // getC1Reserve4
    //----------------
    /** Field c1MontantSolde - M ancien */
    protected static final Field C1MONTANTSOLDE = new Field(2 + 88, 14, "c1MontantSolde");

    /** Sets c1MontantSolde - M ancien
     *  @param c1MontantSolde M ancien
     */
    public void setC1MontantSolde(long c1MontantSolde) {
        setNumber(2 + 88, 14, c1MontantSolde);
    } // setC1MontantSolde

    /** Gets c1MontantSolde - M ancien
     *  @return M ancien
     */
    public long getC1MontantSolde() {
        return getNumber(2 + 88, 14);
    } // getC1MontantSolde
    //----------------
    /** Field c1Reserve5 - X */
    protected static final Field C1RESERVE5 = new Field(2 + 102, 16, "c1Reserve5");

    /** Sets c1Reserve5 - X
     *  @param c1Reserve5 X
     */
    public void setC1Reserve5(String c1Reserve5) {
        setString(2 + 102, 16, c1Reserve5);
    } // setC1Reserve5

    /** Gets c1Reserve5 - X
     *  @return X
     */
    public String getC1Reserve5() {
        return getString(2 + 102, 16);
    } // getC1Reserve5
    //----------------
    /** Field c4CdBanque - M bank code */
    protected static final Field C4CDBANQUE = new Field(2 + 0, 5, "c4CdBanque");

    /** Sets c4CdBanque - M bank code
     *  @param c4CdBanque M bank code
     */
    public void setC4CdBanque(String c4CdBanque) {
        setString(2 + 0, 5, c4CdBanque);
    } // setC4CdBanque

    /** Gets c4CdBanque - M bank code
     *  @return M bank code
     */
    public String getC4CdBanque() {
        return getString(2 + 0, 5);
    } // getC4CdBanque
    //----------------
    /** Field c4OperInterne - O code opération interne */
    protected static final Field C4OPERINTERNE = new Field(2 + 5, 4, "c4OperInterne");

    /** Sets c4OperInterne - O code opération interne
     *  @param c4OperInterne O code opération interne
     */
    public void setC4OperInterne(String c4OperInterne) {
        setString(2 + 5, 4, c4OperInterne);
    } // setC4OperInterne

    /** Gets c4OperInterne - O code opération interne
     *  @return O code opération interne
     */
    public String getC4OperInterne() {
        return getString(2 + 5, 4);
    } // getC4OperInterne
    //----------------
    /** Field c4CdGuichet - M branch */
    protected static final Field C4CDGUICHET = new Field(2 + 9, 5, "c4CdGuichet");

    /** Sets c4CdGuichet - M branch
     *  @param c4CdGuichet M branch
     */
    public void setC4CdGuichet(String c4CdGuichet) {
        setString(2 + 9, 5, c4CdGuichet);
    } // setC4CdGuichet

    /** Gets c4CdGuichet - M branch
     *  @return M branch
     */
    public String getC4CdGuichet() {
        return getString(2 + 9, 5);
    } // getC4CdGuichet
    //----------------
    /** Field c4CdDevise - O currency code ISO 4217 */
    protected static final Field C4CDDEVISE = new Field(2 + 14, 3, "c4CdDevise");

    /** Sets c4CdDevise - O currency code ISO 4217
     *  @param c4CdDevise O currency code ISO 4217
     */
    public void setC4CdDevise(String c4CdDevise) {
        setString(2 + 14, 3, c4CdDevise);
    } // setC4CdDevise

    /** Gets c4CdDevise - O currency code ISO 4217
     *  @return O currency code ISO 4217
     */
    public String getC4CdDevise() {
        return getString(2 + 14, 3);
    } // getC4CdDevise
    //----------------
    /** Field c4NoChiffres - D apres la virgule du montant */
    protected static final Field C4NOCHIFFRES = new Field(2 + 17, 1, "c4NoChiffres");

    /** Sets c4NoChiffres - D apres la virgule du montant
     *  @param c4NoChiffres D apres la virgule du montant
     */
    public void setC4NoChiffres(long c4NoChiffres) {
        setNumber(2 + 17, 1, c4NoChiffres);
    } // setC4NoChiffres

    /** Gets c4NoChiffres - D apres la virgule du montant
     *  @return D apres la virgule du montant
     */
    public long getC4NoChiffres() {
        return getNumber(2 + 17, 1);
    } // getC4NoChiffres
    //----------------
    /** Field c4MonaieOrigine - M */
    protected static final Field C4MONAIEORIGINE = new Field(2 + 18, 1, "c4MonaieOrigine");

    /** Sets c4MonaieOrigine - M
     *  @param c4MonaieOrigine M
     */
    public void setC4MonaieOrigine(String c4MonaieOrigine) {
        setString(2 + 18, 1, c4MonaieOrigine);
    } // setC4MonaieOrigine

    /** Gets c4MonaieOrigine - M
     *  @return M
     */
    public String getC4MonaieOrigine() {
        return getString(2 + 18, 1);
    } // getC4MonaieOrigine
    //----------------
    /** Field c4NoCompte - M */
    protected static final Field C4NOCOMPTE = new Field(2 + 19, 11, "c4NoCompte");

    /** Sets c4NoCompte - M
     *  @param c4NoCompte M
     */
    public void setC4NoCompte(String c4NoCompte) {
        setString(2 + 19, 11, c4NoCompte);
    } // setC4NoCompte

    /** Gets c4NoCompte - M
     *  @return M
     */
    public String getC4NoCompte() {
        return getString(2 + 19, 11);
    } // getC4NoCompte
    //----------------
    /** Field c4CdOperInterbancaire - M */
    protected static final Field C4CDOPERINTERBANCAIRE = new Field(2 + 30, 2, "c4CdOperInterbancaire");

    /** Sets c4CdOperInterbancaire - M
     *  @param c4CdOperInterbancaire M
     */
    public void setC4CdOperInterbancaire(String c4CdOperInterbancaire) {
        setString(2 + 30, 2, c4CdOperInterbancaire);
    } // setC4CdOperInterbancaire

    /** Gets c4CdOperInterbancaire - M
     *  @return M
     */
    public String getC4CdOperInterbancaire() {
        return getString(2 + 30, 2);
    } // getC4CdOperInterbancaire
    //----------------
    /** Field c4DateOper - M DDMMYY */
    protected static final Field C4DATEOPER = new Field(2 + 32, 6, "c4DateOper");

    /** Sets c4DateOper - M DDMMYY
     *  @param c4DateOper M DDMMYY
     */
    public void setC4DateOper(long c4DateOper) {
        setNumber(2 + 32, 6, c4DateOper);
    } // setC4DateOper

    /** Gets c4DateOper - M DDMMYY
     *  @return M DDMMYY
     */
    public long getC4DateOper() {
        return getNumber(2 + 32, 6);
    } // getC4DateOper
    //----------------
    /** Field c4CdMotifRejet - M */
    protected static final Field C4CDMOTIFREJET = new Field(2 + 38, 2, "c4CdMotifRejet");

    /** Sets c4CdMotifRejet - M
     *  @param c4CdMotifRejet M
     */
    public void setC4CdMotifRejet(String c4CdMotifRejet) {
        setString(2 + 38, 2, c4CdMotifRejet);
    } // setC4CdMotifRejet

    /** Gets c4CdMotifRejet - M
     *  @return M
     */
    public String getC4CdMotifRejet() {
        return getString(2 + 38, 2);
    } // getC4CdMotifRejet
    //----------------
    /** Field c4DateValeur - M DDMMYY */
    protected static final Field C4DATEVALEUR = new Field(2 + 40, 6, "c4DateValeur");

    /** Sets c4DateValeur - M DDMMYY
     *  @param c4DateValeur M DDMMYY
     */
    public void setC4DateValeur(long c4DateValeur) {
        setNumber(2 + 40, 6, c4DateValeur);
    } // setC4DateValeur

    /** Gets c4DateValeur - M DDMMYY
     *  @return M DDMMYY
     */
    public long getC4DateValeur() {
        return getNumber(2 + 40, 6);
    } // getC4DateValeur
    //----------------
    /** Field c4Libelle - M */
    protected static final Field C4LIBELLE = new Field(2 + 46, 31, "c4Libelle");

    /** Sets c4Libelle - M
     *  @param c4Libelle M
     */
    public void setC4Libelle(long c4Libelle) {
        setNumber(2 + 46, 31, c4Libelle);
    } // setC4Libelle

    /** Gets c4Libelle - M
     *  @return M
     */
    public long getC4Libelle() {
        return getNumber(2 + 46, 31);
    } // getC4Libelle
    //----------------
    /** Field c4Reserve1 - X */
    protected static final Field C4RESERVE1 = new Field(2 + 77, 2, "c4Reserve1");

    /** Sets c4Reserve1 - X
     *  @param c4Reserve1 X
     */
    public void setC4Reserve1(String c4Reserve1) {
        setString(2 + 77, 2, c4Reserve1);
    } // setC4Reserve1

    /** Gets c4Reserve1 - X
     *  @return X
     */
    public String getC4Reserve1() {
        return getString(2 + 77, 2);
    } // getC4Reserve1
    //----------------
    /** Field c4NoEcrit - M */
    protected static final Field C4NOECRIT = new Field(2 + 79, 7, "c4NoEcrit");

    /** Sets c4NoEcrit - M
     *  @param c4NoEcrit M
     */
    public void setC4NoEcrit(long c4NoEcrit) {
        setNumber(2 + 79, 7, c4NoEcrit);
    } // setC4NoEcrit

    /** Gets c4NoEcrit - M
     *  @return M
     */
    public long getC4NoEcrit() {
        return getNumber(2 + 79, 7);
    } // getC4NoEcrit
    //----------------
    /** Field c4IxExoner - O */
    protected static final Field C4IXEXONER = new Field(2 + 86, 1, "c4IxExoner");

    /** Sets c4IxExoner - O
     *  @param c4IxExoner O
     */
    public void setC4IxExoner(long c4IxExoner) {
        setNumber(2 + 86, 1, c4IxExoner);
    } // setC4IxExoner

    /** Gets c4IxExoner - O
     *  @return O
     */
    public long getC4IxExoner() {
        return getNumber(2 + 86, 1);
    } // getC4IxExoner
    //----------------
    /** Field c4IxIndispon - O */
    protected static final Field C4IXINDISPON = new Field(2 + 87, 1, "c4IxIndispon");

    /** Sets c4IxIndispon - O
     *  @param c4IxIndispon O
     */
    public void setC4IxIndispon(long c4IxIndispon) {
        setNumber(2 + 87, 1, c4IxIndispon);
    } // setC4IxIndispon

    /** Gets c4IxIndispon - O
     *  @return O
     */
    public long getC4IxIndispon() {
        return getNumber(2 + 87, 1);
    } // getC4IxIndispon
    //----------------
    /** Field c4MontantMovem - M movement */
    protected static final Field C4MONTANTMOVEM = new Field(2 + 88, 14, "c4MontantMovem");

    /** Sets c4MontantMovem - M movement
     *  @param c4MontantMovem M movement
     */
    public void setC4MontantMovem(long c4MontantMovem) {
        setNumber(2 + 88, 14, c4MontantMovem);
    } // setC4MontantMovem

    /** Gets c4MontantMovem - M movement
     *  @return M movement
     */
    public long getC4MontantMovem() {
        return getNumber(2 + 88, 14);
    } // getC4MontantMovem
    //----------------
    /** Field c4ZoneRef - O */
    protected static final Field C4ZONEREF = new Field(2 + 102, 16, "c4ZoneRef");

    /** Sets c4ZoneRef - O
     *  @param c4ZoneRef O
     */
    public void setC4ZoneRef(String c4ZoneRef) {
        setString(2 + 102, 16, c4ZoneRef);
    } // setC4ZoneRef

    /** Gets c4ZoneRef - O
     *  @return O
     */
    public String getC4ZoneRef() {
        return getString(2 + 102, 16);
    } // getC4ZoneRef
    //----------------
    /** Field c7CdBanque - M bank code */
    protected static final Field C7CDBANQUE = new Field(2 + 0, 5, "c7CdBanque");

    /** Sets c7CdBanque - M bank code
     *  @param c7CdBanque M bank code
     */
    public void setC7CdBanque(String c7CdBanque) {
        setString(2 + 0, 5, c7CdBanque);
    } // setC7CdBanque

    /** Gets c7CdBanque - M bank code
     *  @return M bank code
     */
    public String getC7CdBanque() {
        return getString(2 + 0, 5);
    } // getC7CdBanque
    //----------------
    /** Field c7Reserve1 - X */
    protected static final Field C7RESERVE1 = new Field(2 + 5, 4, "c7Reserve1");

    /** Sets c7Reserve1 - X
     *  @param c7Reserve1 X
     */
    public void setC7Reserve1(String c7Reserve1) {
        setString(2 + 5, 4, c7Reserve1);
    } // setC7Reserve1

    /** Gets c7Reserve1 - X
     *  @return X
     */
    public String getC7Reserve1() {
        return getString(2 + 5, 4);
    } // getC7Reserve1
    //----------------
    /** Field c7CdGuichet - M branch */
    protected static final Field C7CDGUICHET = new Field(2 + 9, 5, "c7CdGuichet");

    /** Sets c7CdGuichet - M branch
     *  @param c7CdGuichet M branch
     */
    public void setC7CdGuichet(String c7CdGuichet) {
        setString(2 + 9, 5, c7CdGuichet);
    } // setC7CdGuichet

    /** Gets c7CdGuichet - M branch
     *  @return M branch
     */
    public String getC7CdGuichet() {
        return getString(2 + 9, 5);
    } // getC7CdGuichet
    //----------------
    /** Field c7CdDevise - O currency code ISO 4217 */
    protected static final Field C7CDDEVISE = new Field(2 + 14, 3, "c7CdDevise");

    /** Sets c7CdDevise - O currency code ISO 4217
     *  @param c7CdDevise O currency code ISO 4217
     */
    public void setC7CdDevise(String c7CdDevise) {
        setString(2 + 14, 3, c7CdDevise);
    } // setC7CdDevise

    /** Gets c7CdDevise - O currency code ISO 4217
     *  @return O currency code ISO 4217
     */
    public String getC7CdDevise() {
        return getString(2 + 14, 3);
    } // getC7CdDevise
    //----------------
    /** Field c7NoChiffres - D apres la virgule du montant */
    protected static final Field C7NOCHIFFRES = new Field(2 + 17, 1, "c7NoChiffres");

    /** Sets c7NoChiffres - D apres la virgule du montant
     *  @param c7NoChiffres D apres la virgule du montant
     */
    public void setC7NoChiffres(long c7NoChiffres) {
        setNumber(2 + 17, 1, c7NoChiffres);
    } // setC7NoChiffres

    /** Gets c7NoChiffres - D apres la virgule du montant
     *  @return D apres la virgule du montant
     */
    public long getC7NoChiffres() {
        return getNumber(2 + 17, 1);
    } // getC7NoChiffres
    //----------------
    /** Field c7Reserve2 - X */
    protected static final Field C7RESERVE2 = new Field(2 + 18, 1, "c7Reserve2");

    /** Sets c7Reserve2 - X
     *  @param c7Reserve2 X
     */
    public void setC7Reserve2(String c7Reserve2) {
        setString(2 + 18, 1, c7Reserve2);
    } // setC7Reserve2

    /** Gets c7Reserve2 - X
     *  @return X
     */
    public String getC7Reserve2() {
        return getString(2 + 18, 1);
    } // getC7Reserve2
    //----------------
    /** Field c7NoCompte - M */
    protected static final Field C7NOCOMPTE = new Field(2 + 19, 11, "c7NoCompte");

    /** Sets c7NoCompte - M
     *  @param c7NoCompte M
     */
    public void setC7NoCompte(String c7NoCompte) {
        setString(2 + 19, 11, c7NoCompte);
    } // setC7NoCompte

    /** Gets c7NoCompte - M
     *  @return M
     */
    public String getC7NoCompte() {
        return getString(2 + 19, 11);
    } // getC7NoCompte
    //----------------
    /** Field c7Reserve3 - X */
    protected static final Field C7RESERVE3 = new Field(2 + 30, 2, "c7Reserve3");

    /** Sets c7Reserve3 - X
     *  @param c7Reserve3 X
     */
    public void setC7Reserve3(String c7Reserve3) {
        setString(2 + 30, 2, c7Reserve3);
    } // setC7Reserve3

    /** Gets c7Reserve3 - X
     *  @return X
     */
    public String getC7Reserve3() {
        return getString(2 + 30, 2);
    } // getC7Reserve3
    //----------------
    /** Field c7DateSolde - M YYMMDD */
    protected static final Field C7DATESOLDE = new Field(2 + 32, 6, "c7DateSolde");

    /** Sets c7DateSolde - M YYMMDD
     *  @param c7DateSolde M YYMMDD
     */
    public void setC7DateSolde(long c7DateSolde) {
        setNumber(2 + 32, 6, c7DateSolde);
    } // setC7DateSolde

    /** Gets c7DateSolde - M YYMMDD
     *  @return M YYMMDD
     */
    public long getC7DateSolde() {
        return getNumber(2 + 32, 6);
    } // getC7DateSolde
    //----------------
    /** Field c7Reserve4 - X */
    protected static final Field C7RESERVE4 = new Field(2 + 38, 50, "c7Reserve4");

    /** Sets c7Reserve4 - X
     *  @param c7Reserve4 X
     */
    public void setC7Reserve4(String c7Reserve4) {
        setString(2 + 38, 50, c7Reserve4);
    } // setC7Reserve4

    /** Gets c7Reserve4 - X
     *  @return X
     */
    public String getC7Reserve4() {
        return getString(2 + 38, 50);
    } // getC7Reserve4
    //----------------
    /** Field c7MontantSolde - M nouveau */
    protected static final Field C7MONTANTSOLDE = new Field(2 + 88, 14, "c7MontantSolde");

    /** Sets c7MontantSolde - M nouveau
     *  @param c7MontantSolde M nouveau
     */
    public void setC7MontantSolde(long c7MontantSolde) {
        setNumber(2 + 88, 14, c7MontantSolde);
    } // setC7MontantSolde

    /** Gets c7MontantSolde - M nouveau
     *  @return M nouveau
     */
    public long getC7MontantSolde() {
        return getNumber(2 + 88, 14);
    } // getC7MontantSolde
    //----------------
    /** Field c7Reserve5 - X */
    protected static final Field C7RESERVE5 = new Field(2 + 102, 16, "c7Reserve5");

    /** Sets c7Reserve5 - X
     *  @param c7Reserve5 X
     */
    public void setC7Reserve5(String c7Reserve5) {
        setString(2 + 102, 16, c7Reserve5);
    } // setC7Reserve5

    /** Gets c7Reserve5 - X
     *  @return X
     */
    public String getC7Reserve5() {
        return getString(2 + 102, 16);
    } // getC7Reserve5
    //----------------

    /** Gets an XML tag for the record
     *  @param namespace namespace for the generated XML tag with colon, or empty
     *  @return an XML element for a CFONB record
     */
    public String getXMLTag(String namespace) {
        return namespace + "CFONB";
    } // getXMLTag

    /** Fires several SAX events for the record
     *  @param generator transformer with SAX event firing  methods
     */
    public void fireElements(BaseTransformer generator) {
        String localName = "";
        AttributesImpl attrs = null;
        attrs = new AttributesImpl();
                attrs.addAttribute("", "cdEnreg", "cdEnreg"  , "CDATA", replaceAttrText(getCdEnreg()));
        generator.fireStartElement("CFONB", attrs);
        if (false) {
        } else if (getCdEnreg().equals("01")) {
            attrs = new AttributesImpl();
                attrs.addAttribute("", "c1CdBanque", "c1CdBanque", "CDATA", replaceAttrText(getC1CdBanque()));
                attrs.addAttribute("", "c1Reserve1", "c1Reserve1", "CDATA", replaceAttrText(getC1Reserve1()));
                attrs.addAttribute("", "c1CdGuichet", "c1CdGuichet", "CDATA", replaceAttrText(getC1CdGuichet()));
                attrs.addAttribute("", "c1CdDevise", "c1CdDevise", "CDATA", replaceAttrText(getC1CdDevise()));
                attrs.addAttribute("", "c1NoChiffres", "c1NoChiffres", "CDATA", Long.toString(getC1NoChiffres()));
                attrs.addAttribute("", "c1Reserve2", "c1Reserve2", "CDATA", replaceAttrText(getC1Reserve2()));
                attrs.addAttribute("", "c1NoCompte", "c1NoCompte", "CDATA", replaceAttrText(getC1NoCompte()));
                attrs.addAttribute("", "c1Reserve3", "c1Reserve3", "CDATA", replaceAttrText(getC1Reserve3()));
                attrs.addAttribute("", "c1DateSolde", "c1DateSolde", "CDATA", Long.toString(getC1DateSolde()));
                attrs.addAttribute("", "c1Reserve4", "c1Reserve4", "CDATA", replaceAttrText(getC1Reserve4()));
                attrs.addAttribute("", "c1MontantSolde", "c1MontantSolde", "CDATA", Long.toString(getC1MontantSolde()));
                attrs.addAttribute("", "c1Reserve5", "c1Reserve5", "CDATA", replaceAttrText(getC1Reserve5()));
            generator.fireEmptyElement("c1", attrs);
        } else if (getCdEnreg().equals("04")) {
            attrs = new AttributesImpl();
                attrs.addAttribute("", "c4CdBanque", "c4CdBanque", "CDATA", replaceAttrText(getC4CdBanque()));
                attrs.addAttribute("", "c4OperInterne", "c4OperInterne", "CDATA", replaceAttrText(getC4OperInterne()));
                attrs.addAttribute("", "c4CdGuichet", "c4CdGuichet", "CDATA", replaceAttrText(getC4CdGuichet()));
                attrs.addAttribute("", "c4CdDevise", "c4CdDevise", "CDATA", replaceAttrText(getC4CdDevise()));
                attrs.addAttribute("", "c4NoChiffres", "c4NoChiffres", "CDATA", Long.toString(getC4NoChiffres()));
                attrs.addAttribute("", "c4MonaieOrigine", "c4MonaieOrigine", "CDATA", replaceAttrText(getC4MonaieOrigine()));
                attrs.addAttribute("", "c4NoCompte", "c4NoCompte", "CDATA", replaceAttrText(getC4NoCompte()));
                attrs.addAttribute("", "c4CdOperInterbancaire", "c4CdOperInterbancaire", "CDATA", replaceAttrText(getC4CdOperInterbancaire()));
                attrs.addAttribute("", "c4DateOper", "c4DateOper", "CDATA", Long.toString(getC4DateOper()));
                attrs.addAttribute("", "c4CdMotifRejet", "c4CdMotifRejet", "CDATA", replaceAttrText(getC4CdMotifRejet()));
                attrs.addAttribute("", "c4DateValeur", "c4DateValeur", "CDATA", Long.toString(getC4DateValeur()));
                attrs.addAttribute("", "c4Libelle", "c4Libelle", "CDATA", Long.toString(getC4Libelle()));
                attrs.addAttribute("", "c4Reserve1", "c4Reserve1", "CDATA", replaceAttrText(getC4Reserve1()));
                attrs.addAttribute("", "c4NoEcrit", "c4NoEcrit", "CDATA", Long.toString(getC4NoEcrit()));
                attrs.addAttribute("", "c4IxExoner", "c4IxExoner", "CDATA", Long.toString(getC4IxExoner()));
                attrs.addAttribute("", "c4IxIndispon", "c4IxIndispon", "CDATA", Long.toString(getC4IxIndispon()));
                attrs.addAttribute("", "c4MontantMovem", "c4MontantMovem", "CDATA", Long.toString(getC4MontantMovem()));
                attrs.addAttribute("", "c4ZoneRef", "c4ZoneRef", "CDATA", replaceAttrText(getC4ZoneRef()));
            generator.fireEmptyElement("c4", attrs);
        } else if (getCdEnreg().equals("01")) {
            attrs = new AttributesImpl();
                attrs.addAttribute("", "c7CdBanque", "c7CdBanque", "CDATA", replaceAttrText(getC7CdBanque()));
                attrs.addAttribute("", "c7Reserve1", "c7Reserve1", "CDATA", replaceAttrText(getC7Reserve1()));
                attrs.addAttribute("", "c7CdGuichet", "c7CdGuichet", "CDATA", replaceAttrText(getC7CdGuichet()));
                attrs.addAttribute("", "c7CdDevise", "c7CdDevise", "CDATA", replaceAttrText(getC7CdDevise()));
                attrs.addAttribute("", "c7NoChiffres", "c7NoChiffres", "CDATA", Long.toString(getC7NoChiffres()));
                attrs.addAttribute("", "c7Reserve2", "c7Reserve2", "CDATA", replaceAttrText(getC7Reserve2()));
                attrs.addAttribute("", "c7NoCompte", "c7NoCompte", "CDATA", replaceAttrText(getC7NoCompte()));
                attrs.addAttribute("", "c7Reserve3", "c7Reserve3", "CDATA", replaceAttrText(getC7Reserve3()));
                attrs.addAttribute("", "c7DateSolde", "c7DateSolde", "CDATA", Long.toString(getC7DateSolde()));
                attrs.addAttribute("", "c7Reserve4", "c7Reserve4", "CDATA", replaceAttrText(getC7Reserve4()));
                attrs.addAttribute("", "c7MontantSolde", "c7MontantSolde", "CDATA", Long.toString(getC7MontantSolde()));
                attrs.addAttribute("", "c7Reserve5", "c7Reserve5", "CDATA", replaceAttrText(getC7Reserve5()));
            generator.fireEmptyElement("c7", attrs);
        }
        generator.fireEndElement("CFONB");
    } // fireElements

    /** Receive notification of the start of an element.
     *  Looks for the element which contains encoded strings.
     *  @param uri The Namespace URI, or the empty string if the element has no Namespace URI
     *  or if Namespace processing is not being performed.
     *  @param localName the local name (without prefix),
     *  or the empty string if Namespace processing is not being performed.
     *  @param qName the qualified name (with prefix),
     *  or the empty string if qualified names are not available.
     *  @param attrs the attributes attached to the element.
     *  If there are no attributes, it shall be an empty Attributes object.
     *  @throws SAXException for SAX errors
     */
    public void startElement(String uri, String localName, String qName, Attributes attrs) throws SAXException {
        try {
            if (false) {
            } else if (qName.equals("CFONB")) {
                setCdEnreg         (attrs.getValue("cdEnreg"));
            } else if (qName.equals("c1")) {
                setC1CdBanque      (attrs.getValue("c1CdBanque"));
                setC1Reserve1      (attrs.getValue("c1Reserve1"));
                setC1CdGuichet     (attrs.getValue("c1CdGuichet"));
                setC1CdDevise      (attrs.getValue("c1CdDevise"));
                setC1NoChiffres    (Long.parseLong(attrs.getValue("c1NoChiffres")));
                setC1Reserve2      (attrs.getValue("c1Reserve2"));
                setC1NoCompte      (attrs.getValue("c1NoCompte"));
                setC1Reserve3      (attrs.getValue("c1Reserve3"));
                setC1DateSolde     (Long.parseLong(attrs.getValue("c1DateSolde")));
                setC1Reserve4      (attrs.getValue("c1Reserve4"));
                setC1MontantSolde  (Long.parseLong(attrs.getValue("c1MontantSolde")));
                setC1Reserve5      (attrs.getValue("c1Reserve5"));
            } else if (qName.equals("c4")) {
                setC4CdBanque      (attrs.getValue("c4CdBanque"));
                setC4OperInterne   (attrs.getValue("c4OperInterne"));
                setC4CdGuichet     (attrs.getValue("c4CdGuichet"));
                setC4CdDevise      (attrs.getValue("c4CdDevise"));
                setC4NoChiffres    (Long.parseLong(attrs.getValue("c4NoChiffres")));
                setC4MonaieOrigine (attrs.getValue("c4MonaieOrigine"));
                setC4NoCompte      (attrs.getValue("c4NoCompte"));
                setC4CdOperInterbancaire           (attrs.getValue("c4CdOperInterbancaire"));
                setC4DateOper      (Long.parseLong(attrs.getValue("c4DateOper")));
                setC4CdMotifRejet  (attrs.getValue("c4CdMotifRejet"));
                setC4DateValeur    (Long.parseLong(attrs.getValue("c4DateValeur")));
                setC4Libelle       (Long.parseLong(attrs.getValue("c4Libelle")));
                setC4Reserve1      (attrs.getValue("c4Reserve1"));
                setC4NoEcrit       (Long.parseLong(attrs.getValue("c4NoEcrit")));
                setC4IxExoner      (Long.parseLong(attrs.getValue("c4IxExoner")));
                setC4IxIndispon    (Long.parseLong(attrs.getValue("c4IxIndispon")));
                setC4MontantMovem  (Long.parseLong(attrs.getValue("c4MontantMovem")));
                setC4ZoneRef       (attrs.getValue("c4ZoneRef"));
            } else if (qName.equals("c7")) {
                setC7CdBanque      (attrs.getValue("c7CdBanque"));
                setC7Reserve1      (attrs.getValue("c7Reserve1"));
                setC7CdGuichet     (attrs.getValue("c7CdGuichet"));
                setC7CdDevise      (attrs.getValue("c7CdDevise"));
                setC7NoChiffres    (Long.parseLong(attrs.getValue("c7NoChiffres")));
                setC7Reserve2      (attrs.getValue("c7Reserve2"));
                setC7NoCompte      (attrs.getValue("c7NoCompte"));
                setC7Reserve3      (attrs.getValue("c7Reserve3"));
                setC7DateSolde     (Long.parseLong(attrs.getValue("c7DateSolde")));
                setC7Reserve4      (attrs.getValue("c7Reserve4"));
                setC7MontantSolde  (Long.parseLong(attrs.getValue("c7MontantSolde")));
                setC7Reserve5      (attrs.getValue("c7Reserve5"));
            } else {
                // silently ignore other elements
            }
        } catch (Exception exc) {
            throw new SAXException("invalid attribute value ", exc);
        }
    } // startElement

} // class CFONBRecordBase
