-- @(#) $Id$
-- generated by org.teherba.xtrans.parse.Token on 2010-06-30T18:38:53+0200
DROP   TABLE tokens;
CREATE TABLE tokens
	( programName	VARCHAR(64) NOT NULL
	, sortId	VARCHAR(8) NOT NULL
	, tag	VARCHAR( 8) NOT NULL
	, mode	VARCHAR( 8)
	, spacesBefore	INT
	, val	VARCHAR(64)
	, PRIMARY KEY(programName, sortId)
	);
COMMIT;
